# Generated by Django 4.2.7 on 2023-11-30 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homefurnishing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homefurnishing',
            name='slug',
        ),
    ]
