# Generated by Django 4.2.5 on 2023-10-10 10:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologymodel',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='technologymodel',
            name='description_four',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='technologymodel',
            name='description_three',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='technologymodel',
            name='description_two',
            field=tinymce.models.HTMLField(),
        ),
    ]
